"""Quantum programs as differentiable PyTorch layers.

This is the piece that turns a single submission into a workload. A photonic
generative model, a variational classifier or a quantum kernel is not one run:
it is a parameterised program evaluated thousands of times while an optimiser
walks its parameters, and the machine time those loops consume is what fills a
provider's queue.

    layer = PhotonicLayer(client, circuit, [1, 0, 1])
    opt   = torch.optim.Adam(layer.parameters(), lr=0.05)
    for step in range(200):
        loss = criterion(layer(), target)
        opt.zero_grad(); loss.backward(); opt.step()

Each forward is one job. Each backward is one job carrying 2P points, because
the whole gradient goes to /jobs/batch as a single parameterised sweep rather
than as 2P separate submissions.

Three layers, one for each program the service accepts: `CircuitLayer` for a
gate circuit, `PhotonicLayer` for a linear-optical mesh, `SequenceLayer` for an
analog pulse sequence. They differ only in what they submit; the gradient, the
batching and the output shape are identical, so a model written against one
ports to another by swapping the constructor.

**Gradients are central differences, not the parameter-shift rule.** The shift
rule is exact only where an output is a sinusoid of the parameter, which holds
for a Pauli rotation in a gate circuit and does not hold for a beamsplitter
angle in a linear-optical mesh or for a pulse amplitude in an analog sequence.
Central differences cost the same two evaluations per parameter and are correct
for both, at the price of a step-size choice: `eps` defaults to 0.01 rad and is
worth raising when the shot noise at your shot count swamps the difference.

Shot noise is the other thing to keep in view. A gradient estimated from N
shots carries an error of order 1/sqrt(N), so an optimiser that stalls at low
shot counts is usually reading noise rather than a flat landscape.

torch is not a dependency of qsim-sdk; install it yourself to use this module.
"""
from __future__ import annotations

import math
from typing import Any, Sequence

from qiskit import QuantumCircuit

#: Gates whose derivative the parameter-shift rule gives exactly.
#:
#: Each is a rotation generated by a Pauli, `exp(-i * theta * P / 2)`, whose
#: expectation is therefore a sinusoid of theta with a known period. That is
#: the whole condition for the rule, and it is why it does NOT hold for a
#: beamsplitter angle or a pulse amplitude.
_SHIFT_GATES = frozenset({"rx", "ry", "rz", "rxx", "ryy", "rzz", "crx", "cry", "crz"})


def _shift_rule_applies(circuit: Any, weight_names: list[str]) -> bool:
    """Whether every trainable weight sits in exactly one Pauli rotation.

    WHY THIS MATTERS ENOUGH TO DETECT RATHER THAN ASSUME. Central differences
    cost two evaluations per parameter and carry a step-size error on top of
    shot noise. The parameter-shift rule costs the SAME two evaluations and is
    exact. On a gate circuit there is no reason to accept the error, and this
    module shipped accepting it, because the rule genuinely fails for the
    photonic and analog layers and the gate layer inherited their machinery.

    Two conditions, both checked rather than hoped for:

      * the weight appears in exactly ONE instruction. A parameter shared
        across gates needs the sum over its occurrences, which is a different
        rule, so those fall back.
      * that instruction's angle is the bare parameter, not an expression.
        `ry(2*w)` needs the chain rule; `ry(w)` does not. Data-encoding terms
        like `rz(2*(pi - x0)*(pi - x1))` are exactly the expressions that break
        it, and a feature map full of them is common.

    Inputs are ignored: gradients are taken with respect to weights only.
    """
    wanted = set(weight_names)
    seen: dict[str, int] = {}
    for instruction in circuit.data:
        for angle in instruction.operation.params:
            names = {p.name for p in getattr(angle, "parameters", set())}
            touched = names & wanted
            if not touched:
                continue
            if instruction.operation.name not in _SHIFT_GATES:
                return False
            # A bare Parameter has itself as its only parameter and prints as
            # its own name; anything else is an expression.
            if len(names) != 1 or str(angle) != next(iter(names)):
                return False
            for name in touched:
                seen[name] = seen.get(name, 0) + 1
                if seen[name] > 1:
                    return False
    return set(seen) == wanted

__all__ = ["CircuitLayer", "PhotonicLayer", "SequenceLayer"]


def _torch():
    try:
        import torch
    except ImportError as exc:  # pragma: no cover - depends on the environment
        raise ImportError(
            "qsim_sdk.ml needs PyTorch, which qsim-sdk does not install for you. "
            "pip install torch"
        ) from exc
    return torch


class _ProgramLayer:
    """Shared machinery for a parameterised program used as a torch Module.

    Subclasses say three things: how to name the program's free parameters, how
    to submit a list of parameter vectors, and how to turn one point's result
    into a probability mapping.
    """

    #: Filled in by __init__ once torch is known to be importable.
    param_names: list[str]

    def _submit(self, vectors: Sequence[Sequence[float]]) -> list[dict[str, float]]:
        raise NotImplementedError

    # ---------------------------------------------------------------- helpers

    @staticmethod
    def _distribution(item: dict[str, Any]) -> dict[str, float]:
        """Normalised probabilities for one point, or {} if it failed.

        A failed point is a zero vector rather than an exception: the sweep
        endpoint reports failures per point precisely so an optimiser can treat
        one as a bad point and carry on, and raising here would throw away the
        other 2P-1 evaluations that did succeed.
        """
        result = item.get("result") or {}
        counts = result.get("counts") or {}
        total = sum(counts.values())
        if not total:
            return {}
        return {k: v / total for k, v in counts.items()}

    def _probe_outcomes(self, item: dict[str, Any]) -> list[str]:
        """The outcome labels this program can produce, or a clear failure.

        `_distribution` returns {} for a point that produced nothing, and that
        is right in the gradient sweep: one bad point among 2P must not throw
        away the 2P-1 that succeeded.

        A PROBE is different. It is a single point run once at construction to
        learn the outcome list, so {} here means `sorted({})` is `[]` and the
        layer has no outcomes at all. Every forward pass then returns an empty
        tensor, every gradient is zero, and nothing raises. The user trains for
        hours, watches the loss sit still, and concludes quantum ML does not
        work.

        That is what happened to a register built with
        `Register.from_coordinates`: the API refused it with a precise
        diagnostic, `SequenceLayer` swallowed it, constructed happily, and was
        permanently dead. So the tolerance stays in the sweep and stops here,
        and the server's own reason is carried out rather than discarded.
        """
        dist = self._distribution(item)
        if dist:
            return sorted(dist)
        detail = (
            item.get("error")
            or item.get("reason")
            or (item.get("result") or {}).get("reason")
            or f"status {item.get('status')!r} and no counts"
        )
        raise RuntimeError(
            f"this layer produced no outcomes, so every gradient would be zero "
            f"and training would appear to run while doing nothing. The service "
            f"said: {detail}"
        )

    def _vectors_to_probs(self, vectors: Sequence[Sequence[float]]):
        torch = _torch()
        job = self._submit(vectors)
        rows = []
        for item in job:
            dist = self._distribution(item)
            rows.append([dist.get(o, 0.0) for o in self.outcomes])
        return torch.tensor(rows, dtype=torch.float32)


def _make_function():
    """Build the autograd Function lazily, so importing this module without
    torch installed raises a clear ImportError rather than a NameError."""
    torch = _torch()

    class _Evaluate(torch.autograd.Function):
        @staticmethod
        def forward(ctx, theta, layer):
            ctx.layer = layer
            ctx.save_for_backward(theta)
            return layer._vectors_to_probs([theta.detach().tolist()])[0]

        @staticmethod
        def backward(ctx, grad_out):
            (theta,) = ctx.saved_tensors
            layer = ctx.layer
            eps = layer.eps
            base = theta.detach()

            # Every displaced point of the whole gradient in one job: 2P
            # evaluations, one round trip, one queue entry.
            vectors: list[list[float]] = []
            for i in range(base.numel()):
                for sign in (+1.0, -1.0):
                    shifted = base.clone()
                    shifted[i] = shifted[i] + sign * eps
                    vectors.append(shifted.tolist())

            probs = layer._vectors_to_probs(vectors)
            grads = []
            for i in range(base.numel()):
                derivative = (probs[2 * i] - probs[2 * i + 1]) / (2.0 * eps)
                grads.append(torch.dot(grad_out, derivative))
            return torch.stack(grads), None

    return _Evaluate


def _make_batch_function():
    """Autograd over a minibatch of data points.

    The difference from `_make_function` is the shape of the workload, not the
    mathematics. A model that encodes a data point takes a whole minibatch per
    optimiser step, so the forward is B evaluations and the gradient is B x 2P.
    Sent one sample at a time that is 2B submissions a step, each paying its own
    queue entry and its own per-job minimum; sent like this it is two.

    Gradients are taken with respect to the WEIGHTS only. The data parameters
    are held at the values the caller passed, which is what a classifier wants
    and is why `forward` refuses an input tensor that carries `requires_grad`
    rather than silently returning no gradient to whatever produced it.
    """
    torch = _torch()

    class _EvaluateBatch(torch.autograd.Function):
        @staticmethod
        def forward(ctx, theta, x, layer):
            ctx.layer = layer
            ctx.save_for_backward(theta, x)
            weights = theta.detach().tolist()
            return layer._vectors_to_probs(
                [layer._full(weights, sample) for sample in x.tolist()]
            )

        @staticmethod
        def backward(ctx, grad_out):
            theta, x = ctx.saved_tensors
            layer = ctx.layer
            eps = layer.eps
            base = theta.detach()
            n_weights = base.numel()
            samples = x.tolist()

            # The whole minibatch's gradient in one job: B x 2P evaluations,
            # ordered sample-major so the unpacking below is an index rather
            # than a search.
            # The shift and the divisor are the ONLY difference between the
            # parameter-shift rule and a central difference. Both cost two
            # evaluations per parameter; the shift rule is exact where it
            # applies and a central difference always carries a step-size
            # error on top of shot noise. See `_shift_rule_applies`.
            step, divisor = (
                (math.pi / 2, 2.0) if layer.parameter_shift else (eps, 2.0 * eps)
            )

            rows: list[list[float]] = []
            for sample in samples:
                for i in range(n_weights):
                    for sign in (+1.0, -1.0):
                        shifted = base.clone()
                        shifted[i] = shifted[i] + sign * step
                        rows.append(layer._full(shifted.tolist(), sample))

            probs = layer._vectors_to_probs(rows)
            grads = torch.zeros(n_weights, dtype=torch.float32)
            for b in range(len(samples)):
                for i in range(n_weights):
                    k = b * 2 * n_weights + 2 * i
                    derivative = (probs[k] - probs[k + 1]) / divisor
                    grads[i] = grads[i] + torch.dot(grad_out[b], derivative)
            return grads, None, None

    return _EvaluateBatch


class CircuitLayer:
    """A parameterised Qiskit circuit as a torch Module.

    The gate-circuit member of the family, and the one most quantum machine
    learning is written against: variational classifiers, circuit Born
    machines, the generator half of a QGAN, the sub-generators of a patch GAN.
    Without it each of those starts with a few hundred lines of central
    differences, batching and autograd plumbing before a line of the actual
    model gets written.

        theta = ParameterVector("t", 4)
        qc = QuantumCircuit(2)
        qc.ry(theta[0], 0); qc.ry(theta[1], 1); qc.cx(0, 1)
        qc.ry(theta[2], 0); qc.ry(theta[3], 1)
        qc.measure_all()

        layer = CircuitLayer(client, qc, shots=1024)
        opt = torch.optim.Adam(layer.parameters(), lr=0.1)

    The output is the probability of each measured bitstring, in a fixed order,
    which is the vector a classical head consumes. An expectation value is a
    dot product against that vector and costs nothing extra:

        z0 = sum(p * (1 if b[-1] == "0" else -1)
                 for b, p in zip(layer.outcomes, layer()))

    **A model that reads data declares which parameters carry it.** Without
    that split every angle in the circuit is a trainable weight, so an encoding
    angle would be optimised as though it were one, which is wrong rather than
    merely inconvenient. Name the data parameters and the rest are the weights:

        x = ParameterVector("x", 2)      # the data point
        w = ParameterVector("w", 4)      # the trainable part
        qc = QuantumCircuit(2)
        qc.ry(x[0], 0); qc.ry(x[1], 1)
        qc.ry(w[0], 0); qc.ry(w[1], 1); qc.cx(0, 1)
        qc.ry(w[2], 0); qc.ry(w[3], 1)
        qc.measure_all()

        layer = CircuitLayer(client, qc, inputs=[p.name for p in x])
        probs = layer(X)                 # X is (batch, 2) -> (batch, outcomes)

    A minibatch is one job, and its gradient is one more, whatever the batch
    size. **Know what a step costs before starting a long run**: a batch of B
    samples over P weights is B evaluations forward and B x 2P backward, and
    every one of those is a circuit charged at the per-circuit minimum. 32
    samples over 8 weights is 544 circuits a step. Price it with
    `Client.estimate_batch` first; that endpoint exists for exactly this.

    Gradients are taken with respect to the weights. An input tensor carrying
    `requires_grad` is refused rather than quietly given no gradient, because a
    classical network in front of this layer would otherwise never train while
    appearing to.

    **Binding happens client-side**, in `Client.run_sweep`, because OpenQASM 2
    cannot carry an unbound parameter. The wire therefore only ever sees bound
    circuits, and `circuit.parameters` (Qiskit orders it by name) fixes which
    entry of theta drives which gate.

    One hazard specific to gate circuits, worth reading before a long run. The
    outcome list is learned from a single probe at the initial parameters, and
    a circuit initialised near a basis state may simply not produce most of its
    bitstrings in that one run. Those outcomes are then missing from the
    layer's output for the rest of training, and the probabilities returned do
    not sum to one. Pass `outcomes=` explicitly whenever the output space is
    known, which for n measured qubits is every n-bit string.
    """

    def __new__(cls, *args: Any, **kwargs: Any):
        torch = _torch()

        class _Module(torch.nn.Module, _ProgramLayer):
            def __init__(
                self,
                client: Any,
                circuit: Any,
                *,
                inputs: Sequence[str] | None = None,
                shots: int = 1024,
                engine: str = "exact.cpu",
                outcomes: Sequence[str] | None = None,
                init: Sequence[float] | None = None,
                eps: float = 0.01,
                timeout: float = 600.0,
            ) -> None:
                super().__init__()
                if not isinstance(circuit, QuantumCircuit):
                    raise TypeError(
                        f"CircuitLayer needs a qiskit QuantumCircuit so its "
                        f"parameters can be bound before submission, got "
                        f"{type(circuit).__name__}. For another framework, use "
                        f"PhotonicLayer or SequenceLayer, or bind with that "
                        f"framework's own API and call run_batch yourself."
                    )
                self.client = client
                self.circuit = circuit
                self.shots = shots
                self.engine = engine
                self.eps = float(eps)
                self.timeout = timeout
                # Qiskit's ParameterView sorts by name, so this order is stable
                # across calls and is the order `init` is read in.
                self._params = list(circuit.parameters)
                self.param_names = [p.name for p in self._params]
                if not self.param_names:
                    raise ValueError(
                        "the circuit has no free parameters, so there is nothing to "
                        "train. Declare them with qiskit.circuit.Parameter or "
                        "ParameterVector."
                    )
                self.input_names = list(inputs) if inputs else []
                unknown = [n for n in self.input_names if n not in self.param_names]
                if unknown:
                    # A typo here is silent otherwise: the named parameter would
                    # stay in the weights, be trained, and the data would never
                    # reach the circuit at all.
                    raise ValueError(
                        f"inputs names {unknown} are not parameters of this circuit. "
                        f"It has {self.param_names}."
                    )
                self.weight_names = [
                    n for n in self.param_names if n not in set(self.input_names)
                ]
                if not self.weight_names:
                    raise ValueError(
                        "every parameter of this circuit was declared an input, so "
                        "there are no weights left to train."
                    )
                if "measure" not in circuit.count_ops():
                    # Caught here rather than at the probe because the failure it
                    # produces downstream is empty counts, which reads as "the
                    # device returned nothing" and sends people looking at the
                    # engine instead of at their circuit.
                    raise ValueError(
                        "the circuit has no measurements, so it returns no counts "
                        "and there is nothing to differentiate. Add "
                        "qc.measure_all() or measure the qubits you need."
                    )
                start = list(init) if init is not None else [0.5] * len(self.weight_names)
                if len(start) != len(self.weight_names):
                    raise ValueError(
                        f"init has {len(start)} values for {len(self.weight_names)} "
                        f"trainable weights {self.weight_names}"
                    )
                self.theta = torch.nn.Parameter(torch.tensor(start, dtype=torch.float32))
                # EXACT GRADIENTS WHERE THEY ARE AVAILABLE. The shift rule and
                # a central difference cost the same two evaluations per
                # weight; only one of them is exact. Detected rather than
                # assumed, and reported on the layer so a caller can see which
                # they got rather than having to work it out.
                self.parameter_shift = _shift_rule_applies(circuit, self.weight_names)
                self.gradient_method = (
                    "parameter-shift" if self.parameter_shift else "central-difference"
                )
                self.outcomes = list(outcomes) if outcomes else self._probe()
                self._fn = _make_batch_function()

            def _full(self, weights: Sequence[float], sample: Sequence[float]):
                """One full parameter vector, in `circuit.parameters` order.

                Both halves are assembled by NAME rather than by position.
                Qiskit sorts a ParameterView by name, so declaring an input
                reorders nothing and the caller's `inputs` list, the weights and
                the wire cannot drift apart.
                """
                values = dict(zip(self.weight_names, weights))
                values.update(zip(self.input_names, sample))
                return [values[p.name] for p in self._params]

            def _probe(self) -> list[str]:
                """One run at the initial weights, to learn which bitstrings
                this circuit produces.

                Data parameters are probed at zero, because there is no data at
                construction time. That is a valid circuit but not necessarily a
                representative one, which is the second reason the class
                docstring asks for `outcomes=` whenever the space is known.
                """
                zeros = [0.0] * len(self.input_names)
                job = self._submit([self._full(self.theta.detach().tolist(), zeros)])
                return self._probe_outcomes(job[0])

            def _submit(self, vectors):
                bindings = [dict(zip(self._params, v)) for v in vectors]
                job = self.client.run_sweep(
                    self.circuit,
                    bindings,
                    shots=self.shots,
                    engine=self.engine,
                    timeout=self.timeout,
                )
                return job["results"]

            def forward(self, x: Any = None):
                """Probabilities for one point, or for a whole minibatch.

                With no inputs declared, `layer()` is one evaluation and returns
                a vector. With inputs, `layer(x)` takes (features,) and returns
                a vector, or (batch, features) and returns (batch, outcomes).
                """
                if not self.input_names:
                    if x is not None:
                        raise ValueError(
                            "this layer declares no inputs, so it takes no argument. "
                            "Pass inputs=[...] naming the circuit parameters that "
                            "carry data if this model is meant to read any."
                        )
                    # A single sample with no features, so one code path covers
                    # the data-free model and the classifier alike.
                    data = torch.zeros(1, 0, dtype=torch.float32)
                    return self._fn.apply(self.theta, data, self)[0]

                if x is None:
                    raise ValueError(
                        f"this layer declares inputs {self.input_names}, so it needs "
                        f"a data point: call layer(x) with {len(self.input_names)} "
                        f"features, or a (batch, {len(self.input_names)}) tensor."
                    )
                data = x if isinstance(x, torch.Tensor) else torch.tensor(x)
                if data.requires_grad:
                    raise NotImplementedError(
                        "this layer differentiates its weights, not its inputs, so a "
                        "classical layer in front of it would never receive a "
                        "gradient. Detach the input, or move the classical part "
                        "after this layer where it trains normally."
                    )
                data = data.to(torch.float32)
                single = data.dim() == 1
                if single:
                    data = data.unsqueeze(0)
                if data.dim() != 2 or data.shape[1] != len(self.input_names):
                    raise ValueError(
                        f"expected a (batch, {len(self.input_names)}) input for "
                        f"{self.input_names}, got shape {tuple(data.shape)}"
                    )
                out = self._fn.apply(self.theta, data, self)
                return out[0] if single else out

        return _Module(*args, **kwargs)


class PhotonicLayer:
    """A parameterised Perceval circuit as a torch Module.

    The layer's output is the probability of each detected Fock state, in a
    fixed order, which is the vector a classical network downstream consumes.
    The outcome list is fixed at construction rather than read from each run:
    which states appear varies with shot noise, and a layer whose output
    dimension changed between steps could not be trained.
    """

    def __new__(cls, *args: Any, **kwargs: Any):
        torch = _torch()

        class _Module(torch.nn.Module, _ProgramLayer):
            def __init__(
                self,
                client: Any,
                circuit: Any,
                input_state: Any,
                *,
                shots: int = 1000,
                engine: str = "photonic.slos.cpu",
                outcomes: Sequence[str] | None = None,
                init: Sequence[float] | None = None,
                eps: float = 0.01,
                timeout: float = 600.0,
            ) -> None:
                super().__init__()
                self.client = client
                self.circuit = circuit
                self.input_state = input_state
                self.shots = shots
                self.engine = engine
                self.eps = float(eps)
                self.timeout = timeout
                self.param_names = [p.name for p in circuit.get_parameters()]
                if not self.param_names:
                    raise ValueError(
                        "the circuit has no free parameters, so there is nothing to "
                        "train. Declare them with perceval.P('name')."
                    )
                start = list(init) if init is not None else [0.5] * len(self.param_names)
                if len(start) != len(self.param_names):
                    raise ValueError(
                        f"init has {len(start)} values for {len(self.param_names)} "
                        f"parameters {self.param_names}"
                    )
                self.theta = torch.nn.Parameter(torch.tensor(start, dtype=torch.float32))
                self.outcomes = list(outcomes) if outcomes else self._probe()
                self._fn = _make_function()

            def _probe(self) -> list[str]:
                """One run at the initial parameters, to learn which Fock states
                this circuit and input can produce."""
                job = self._submit([self.theta.detach().tolist()])
                return self._probe_outcomes(job[0])

            def _submit(self, vectors):
                bindings = [dict(zip(self.param_names, v)) for v in vectors]
                job = self.client.run_parametric_sweep(
                    self.circuit,
                    bindings,
                    kind="photonic",
                    input_state=self.input_state,
                    shots=self.shots,
                    engine=self.engine,
                    timeout=self.timeout,
                )
                return job["results"]

            def forward(self):
                return self._fn.apply(self.theta, self)

        return _Module(*args, **kwargs)


class SequenceLayer:
    """A parameterised Pulser sequence as a torch Module.

    The analog counterpart of PhotonicLayer: the output is the probability of
    each measured bitstring over the register, with 1 = Rydberg. Same gradient
    method and the same one-job-per-gradient behaviour.
    """

    def __new__(cls, *args: Any, **kwargs: Any):
        torch = _torch()

        class _Module(torch.nn.Module, _ProgramLayer):
            def __init__(
                self,
                client: Any,
                sequence: Any,
                *,
                shots: int = 1000,
                engine: str = "analog.pulser.cpu",
                outcomes: Sequence[str] | None = None,
                init: Sequence[float] | None = None,
                eps: float = 0.01,
                timeout: float = 600.0,
            ) -> None:
                super().__init__()
                self.client = client
                self.sequence = sequence
                self.shots = shots
                self.engine = engine
                self.eps = float(eps)
                self.timeout = timeout
                self.param_names = list(getattr(sequence, "declared_variables", {}) or {})
                if not self.param_names:
                    raise ValueError(
                        "the sequence declares no variables, so there is nothing to "
                        "train. Declare them with seq.declare_variable('name')."
                    )
                start = list(init) if init is not None else [1.0] * len(self.param_names)
                if len(start) != len(self.param_names):
                    raise ValueError(
                        f"init has {len(start)} values for {len(self.param_names)} "
                        f"variables {self.param_names}"
                    )
                self.theta = torch.nn.Parameter(torch.tensor(start, dtype=torch.float32))
                self.outcomes = list(outcomes) if outcomes else self._probe()
                self._fn = _make_function()

            def _probe(self) -> list[str]:
                job = self._submit([self.theta.detach().tolist()])
                return self._probe_outcomes(job[0])

            def _submit(self, vectors):
                bindings = [dict(zip(self.param_names, v)) for v in vectors]
                job = self.client.run_parametric_sweep(
                    self.sequence,
                    bindings,
                    kind="pulser",
                    shots=self.shots,
                    engine=self.engine,
                    timeout=self.timeout,
                )
                return job["results"]

            def forward(self):
                return self._fn.apply(self.theta, self)

        return _Module(*args, **kwargs)
